### ISSUE TITLE
Dependencies are very out of date

### ISSUE THREAD

**Issue by leonardoInf** [qwefgh90/ng-terminal#21]
Hi, 
The dependencies are very out of date. There are many high vulnerabilities and even one critical. I  highly recommend you to use [Dependabot](https://dependabot.com/).

I really like your Angular component btw.

Edit: I have created a [fork](https://github.com/leonardoInf/ng-terminal) of your project where I will try to update the dependencies.

**Comment by qwefgh90** [comment]
Hello, 
**Thank you for your support and attention.** It seems to be necessary to bump many dependencies up. As you said I tried to install Dependabot and a lot of pull requests were made. Some seem to include security updates. I think I need to spend a little times learning them.

And before reviewing pull requests, I would check travis-ci because tests for recent commits failed.

**Comment by leonardoInf** [comment]
I had a look at your recent commit and I am kind of surprised that updating the Ubuntu version fixed the timeout. The Dependabot fixes now seem to merge without conflicts.

**Comment by qwefgh90** [comment]
Yeah i think so. I've felt the dependabot is very usuful, but I can't handle every pull request from it properly. So I often turn on it manually. If you find an issues about breaking, please let me know.
Thank you so much again.
