### ISSUE TITLE
font issue when used in mat-dialog

### ISSUE THREAD

**Issue by kpayson** [qwefgh90/ng-terminal#52]
If I use ng-terminal in a mat-dalog and I set any option such as term.setOption('fontSize', 32); then the letter spacing is messed up in therminal window.  All of the letters get scrunched together.  Here is a stackblitz showing the problem.

https://stackblitz.com/edit/angular-ivy-tmtt7i?file=src%2Fapp%2Fcli-terminal.component.ts

I don't know why the combination of using a mat-dialog and the ng-terminal should cause a problem.  

![image](https://user-images.githubusercontent.com/923449/108566861-1ae8d880-72d5-11eb-86ea-8e1b3b7f4f2a.png)

**Comment by qwefgh90** [comment]
I think this bug is likely to happen when the dialog is opening. After setOption('fontSize'... is called, [boundingClientRect()](https://github.com/xtermjs/xterm.js/blob/782797ca111157fd08c5df5537a3d0da7546e74d/src/browser/services/CharSizeService.ts#L76) is used to calculate the dimension of xterm. And I think `boundingClientRect()` is affected by material's "transform: scale(..." which is used to make opening animation effect.

So if you call setOption('fontSize'... before opening animation is finished, the problem happens. It's similar issue at https://github.com/xtermjs/xterm.js/issues/3160

I don't know the way to get the timing when the opening animation is finished and how to improve the code nicely. Calling `term.setOption('fontSize', 40);` or`term.resize(this.term.rows, this.term.cols);` with `setTimeout(..., 1000)` can be one of solutions.
