### ISSUE TITLE
Add writeln function

### ISSUE THREAD

**Issue by williangd** [qwefgh90/ng-terminal#7]
It would be interesting to have the writeln function, as well as xterm.js.

I'm getting the data through a websocket, with the write function the component is not breaking the lines. Is there any way to break lines, like the writeln function of xterm.js?

I tried with `\n` and `<br>`, but neither worked properly.

**Comment by qwefgh90** [comment]
It works in the specific way because it is terminal emulator.
You can breaking the lines by replacing `\n` or `<br>` with `\x1b[1E`. I have learned it is one of control sequences.
You can explorer more control sequences [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Controls-beginning-with-ESC).

```
    ...
    this.child.write('\x1b[1E'); // This is adding new line.
    ...
```

I think `writeln()` is looking good because that the control sequence for just newline is easy to mistake and a little rough way.
