### ISSUE TITLE
Backspace not working

### ISSUE THREAD

**Issue by vmagesh** [qwefgh90/ng-terminal#8]
Backspace, Delete, Enter Keys are not working

**Comment by qwefgh90** [comment]
Hello @vmagesh . 
You are feeling that it is not working when typing Backspace and Delete and Keys on [the sample page](https://qwefgh90.github.io/ng-terminal/) Is it right?

I can say that it is normal in the web terminal emulator.
The terminal emulator can accept only specific commands because it is the web terminal emulator not the general editor. please check out #7 .

If it is not what you are asking, please comment.

**Comment by qwefgh90** [comment]
I have updated the [sample page](https://qwefgh90.github.io/ng-terminal/). Now you can get the [example](https://github.com/qwefgh90/ng-terminal/blob/master/src/app/example.component.ts#L49) where some keys you said work.
