### ISSUE TITLE
Change Remove CSS

### ISSUE THREAD

**Issue by thagh05t** [qwefgh90/ng-terminal#9]
Hey,

I am attempting to use ng-terminal, but found some CSS that I cannot override, which is a bit inconvenient.

I would like either the CSS applied to the terminal-outer class to be configurable or removed.

**Comment by qwefgh90** [comment]
Hello @thagh05t 

Until now, there have been no a nice functionality to override styles of terminal-outer. But there is something you can try. Maybe you already know a following way.

You can override terminal-outer by adding styles in `src/styles.css`. 

First, wrap <ng-terminal> with a div box which has a class name.
```
<div class="ng-teriminal-wrapper">
    <ng-terminal #term [dataSource]="writeSubject" (keyInput)="onKeyInput($event)" [displayOption]="displayOptionBounded"
    [ngClass]="{'ng-terminal': (displayOption.activateDraggableOnEdge == undefined && displayOption.fixedGrid == undefined)}">
    </ng-terminal>
</div>
```

And you can add following styles which you'd like to apply to `/src/styles.css`. If you want to override existing styles, use `!important`
```
.ng-teriminal-wrapper .terminal-outer {
    border: unset !important;
    width: 300px;
}
```

I know this way is a little tricky, but i am not sure that it is a bad design because it is used in another mature open source.

If you already know this way, please let me know what styles you want to override.
